added router byId but it returns null
yana-kozlova/WaterTracker-back pull request #17
Opened 2024-12-12 15:43 UTC by ihor-mikheyev

2024-12-13 19:14 UTC, yana-kozlova requested changes

2024-12-13 19:14 UTC, yana-kozlova commented on src/controllers/users.js
> +export const getAllUsersController = async (req, res) => {
Нам наче ж не треба забирати всіх юзерів...

2024-12-13 19:14 UTC, yana-kozlova commented on src/routers/users.js
> +
Питання на подумать: 
Де фронтенд візьме айді поточного користувача? При логіні він отримає тільки токен. 

А запит з фронта предполагається по user/:id

2024-12-13 19:58 UTC, ihor-mikheyev commented on src/controllers/users.js
> +export const getAllUsersController = async (req, res) => {
Ок, я його приберу.  Використовував його для тесту.

2024-12-15 10:19 UTC, yana-kozlova approved these changes

2024-12-15 11:16 UTC, merged